#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clr-service-restart
Version  : 6
Release  : 13
URL      : https://github.com/clearlinux/clr-service-restart/releases/download/v6/clr-service-restart-6.tar.xz
Source0  : https://github.com/clearlinux/clr-service-restart/releases/download/v6/clr-service-restart-6.tar.xz
Source1  : clr-service-restart-motd.service
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: clr-service-restart-bin = %{version}-%{release}
Requires: clr-service-restart-data = %{version}-%{release}
Requires: clr-service-restart-license = %{version}-%{release}
Requires: clr-service-restart-man = %{version}-%{release}
Requires: clr-service-restart-services = %{version}-%{release}
Patch1: 0001-Motd-updating-script-for-clearlinux.patch

%description
No detailed description available

%package bin
Summary: bin components for the clr-service-restart package.
Group: Binaries
Requires: clr-service-restart-data = %{version}-%{release}
Requires: clr-service-restart-license = %{version}-%{release}
Requires: clr-service-restart-services = %{version}-%{release}

%description bin
bin components for the clr-service-restart package.


%package data
Summary: data components for the clr-service-restart package.
Group: Data

%description data
data components for the clr-service-restart package.


%package license
Summary: license components for the clr-service-restart package.
Group: Default

%description license
license components for the clr-service-restart package.


%package man
Summary: man components for the clr-service-restart package.
Group: Default

%description man
man components for the clr-service-restart package.


%package services
Summary: services components for the clr-service-restart package.
Group: Systemd services

%description services
services components for the clr-service-restart package.


%prep
%setup -q -n clr-service-restart-6
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1553902562
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1553902562
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/clr-service-restart
cp COPYING %{buildroot}/usr/share/package-licenses/clr-service-restart/COPYING
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/clr-service-restart-motd.service
## install_append content
mkdir -p %{buildroot}/usr/bin
install -m0755 clr-service-restart-motd.sh %{buildroot}/usr/bin/clr-service-restart-motd.sh
mkdir -p %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants
ln -sf ../clr-service-restart-motd.service %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants/clr-service-restart-motd.service
mkdir -p %{buildroot}/usr/share/clr-service-restart/
ln -sf /dev/null %{buildroot}/usr/share/clr-service-restart/dbus.service
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/clr-service-restart
/usr/bin/clr-service-restart-motd.sh

%files data
%defattr(-,root,root,-)
/usr/share/clr-service-restart/dbus.service

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/clr-service-restart/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/clr-service-restart.1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/clr-service-restart-motd.service
/usr/lib/systemd/system/update-triggers.target.wants/clr-service-restart-motd.service
