#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clr-service-restart
Version  : 1
Release  : 1
URL      : https://github.com/clearlinux/clr-service-restart/releases/download/v1/clr-service-restart-1.tar.xz
Source0  : https://github.com/clearlinux/clr-service-restart/releases/download/v1/clr-service-restart-1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: clr-service-restart-bin

%description
No detailed description available

%package bin
Summary: bin components for the clr-service-restart package.
Group: Binaries

%description bin
bin components for the clr-service-restart package.


%prep
%setup -q -n clr-service-restart-1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1516124998
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1516124998
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/clr-service-restart
